services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: desafio_tecnico_CEFOPE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=desafio_tecnico_CEFOPE;Username=postgres;Password=postgres
      - Jwt__Secret=CursosPlatform_SuperSecretKey_2024_MinLength32Chars!
      - Jwt__Issuer=CursosPlatform
      - Jwt__Audience=CursosPlatformUsers
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5174
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:
